"""Changes to booking schema.

Revision ID: cb529ba1a331
Revises: cbb42e8999e7
Create Date: 2022-03-13 09:42:10.664216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cb529ba1a331'
down_revision = 'cbb42e8999e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('income_id', sa.Integer(), nullable=True))
    op.add_column('booking', sa.Column('nightly_rate', sa.Float(), nullable=True))
    op.create_foreign_key(None, 'booking', 'contact', ['contact_id'], ['id'])
    op.create_foreign_key(None, 'booking', 'income', ['income_id'], ['id'])
    op.drop_constraint('contact_ibfk_3', 'contact', type_='foreignkey')
    op.drop_column('contact', 'booking_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contact', sa.Column('booking_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('contact_ibfk_3', 'contact', 'booking', ['booking_id'], ['id'])
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_constraint(None, 'booking', type_='foreignkey')
    op.drop_column('booking', 'nightly_rate')
    op.drop_column('booking', 'income_id')
    op.drop_column('booking', 'contact_id')
    # ### end Alembic commands ###
