"""Added link table.

Revision ID: cbb42e8999e7
Revises: 
Create Date: 2022-01-30 18:10:52.575210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cbb42e8999e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('property', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('property', sa.Column('url', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
