"""Added unique constraint to contact first and last names.

Revision ID: f21b7eefc7a4
Revises: cb529ba1a331
Create Date: 2022-03-15 05:03:23.275979

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f21b7eefc7a4'
down_revision = 'cb529ba1a331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('booking', 'property_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.create_unique_constraint(None, 'contact', ['first_name', 'last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contact', type_='unique')
    op.alter_column('booking', 'property_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###
